server:
  port: 8082

account:
  limit: 3

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:postgres}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

#  rabbitmq:
#    host: ${RABBIT_HOST:localhost}
#    port: ${RABBIT_PORT:5672}
#    username: ${RABBIT_USERNAME:guest}
#    password: ${RABBIT_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: metrics, students
  metrics:
    export:
      prometheus:
        enabled: true
